---
# handlers file for RHEL10-CIS

- name: "Remount tmp filesystem"
  ansible.builtin.include_tasks:
    file: remount_tmp.yml
  listen: "Remount /tmp"

- name: "Adding options for /dev/shm"
  vars:
    mount_point: '/dev/shm'
  ansible.posix.mount:
    path: "{{ mount_point }}"
    src: "{{ prelim_mount_point_fs_and_options[mount_point]['src'] }}"
    state: present
    fstype: "{{ prelim_mount_point_fs_and_options[mount_point]['fs_type'] }}"
    opts: "{{ prelim_mount_point_fs_and_options[mount_point]['options'] | unique | join(',') }}"
  listen: "Remount /dev/shm"

- name: "Remounting /dev/shm"
  vars:
    mount_point: '/dev/shm'
  ansible.posix.mount:
    path: "{{ mount_point }}"
    state: remounted
  listen: "Remount /dev/shm"

- name: "Adding options for /home"
  vars:
    mount_point: '/home'
  ansible.posix.mount:
    path: "{{ mount_point }}"
    src: "{{ prelim_mount_point_fs_and_options[mount_point]['src'] }}"
    state: present
    fstype: "{{ prelim_mount_point_fs_and_options[mount_point]['fs_type'] }}"
    opts: "{{ prelim_mount_point_fs_and_options[mount_point]['options'] | unique | join(',') }}"
  listen: "Remount /home"

- name: "Remounting /home"
  vars:
    mount_point: '/home'
  ansible.posix.mount:
    path: "{{ mount_point }}"
    state: remounted
  listen: "Remount /home"

- name: "Adding options for /var"
  vars:
    mount_point: '/var'
  ansible.posix.mount:
    path: "{{ mount_point }}"
    src: "{{ prelim_mount_point_fs_and_options[mount_point]['src'] }}"
    state: present
    fstype: "{{ prelim_mount_point_fs_and_options[mount_point]['fs_type'] }}"
    opts: "{{ prelim_mount_point_fs_and_options[mount_point]['options'] | unique | join(',') }}"
  listen: "Remount /var"

- name: "Remounting /var"
  vars:
    mount_point: '/var'
  ansible.posix.mount:
    path: "{{ mount_point }}"
    state: remounted
  listen: "Remount /var"

- name: "Adding options for /var/tmp"
  vars:
    mount_point: '/var/tmp'
  ansible.posix.mount:
    path: "{{ mount_point }}"
    src: "{{ prelim_mount_point_fs_and_options[mount_point]['src'] }}"
    state: present
    fstype: "{{ prelim_mount_point_fs_and_options[mount_point]['fs_type'] }}"
    opts: "{{ prelim_mount_point_fs_and_options[mount_point]['options'] | unique | join(',') }}"
  listen: "Remount /var/tmp"

- name: "Remounting /var/tmp"
  vars:
    mount_point: '/var/tmp'
  ansible.posix.mount:
    path: "{{ mount_point }}"
    state: remounted
  listen: "Remount /var/tmp"

- name: "Adding options for /var/log"
  vars:
    mount_point: '/var/log'
  ansible.posix.mount:
    path: "{{ mount_point }}"
    src: "{{ prelim_mount_point_fs_and_options[mount_point]['src'] }}"
    state: present
    fstype: "{{ prelim_mount_point_fs_and_options[mount_point]['fs_type'] }}"
    opts: "{{ prelim_mount_point_fs_and_options[mount_point]['options'] | unique | join(',') }}"
  listen: "Remount /var/log"

- name: "Remounting /var/log"
  vars:
    mount_point: '/var/log'
  ansible.posix.mount:
    path: "{{ mount_point }}"
    state: remounted
  listen: "Remount /var/log"

- name: "Adding options for /var/log/audit"
  vars:
    mount_point: '/var/log/audit'
  ansible.posix.mount:
    path: "{{ mount_point }}"
    src: "{{ prelim_mount_point_fs_and_options[mount_point]['src'] }}"
    state: present
    fstype: "{{ prelim_mount_point_fs_and_options[mount_point]['fs_type'] }}"
    opts: "{{ prelim_mount_point_fs_and_options[mount_point]['options'] | unique | join(',') }}"
  listen: "Remount /var/log/audit"

- name: "Remounting /var/log/audit"
  vars:
    mount_point: '/var/log/audit'
  ansible.posix.mount:
    path: "{{ mount_point }}"
    state: remounted
  listen: "Remount /var/log/audit"

- name: "Remounting /boot/efi"
  vars:
    mount_point: '/boot/efi'
  ansible.posix.mount:
    path: "{{ mount_point }}"
    state: remounted
  notify: Set reboot required
  listen: "Remount /boot/efi"

- name: Restart chronyd
  ansible.builtin.systemd:
    name: chronyd
    state: restarted

- name: Sysctl update required
  ansible.builtin.set_fact:
    rhel10cis_sysctl_update: true

- name: Reload sysctl
  ansible.builtin.command: sysctl --system
  changed_when: true

- name: Coredump Reload
  ansible.builtin.systemd:
    name: systemd-coredump.socket
    state: restarted

- name: Selinux relabel
  when:
    - rhel10cis_selinux_relabel_enabled
    - ansible_selinux.status == 'disabled'
    - rhel10cis_disruption_high
  ansible.builtin.file:
    path: /.autorelabel
  notify: Set reboot required

- name: Update Crypto Policy
  ansible.builtin.set_fact:
    rhel10cis_full_crypto_policy: "{{ rhel10cis_crypto_policy }}{{ rhel10cis_crypto_policy_module }}{% if rhel10cis_additional_crypto_policy_module | length > 0 %}:{{ rhel10cis_additional_crypto_policy_module }}{% endif %}"
  notify: Set Crypto Policy

- name: Set Crypto Policy
  when: prelim_system_wide_crypto_policy.stdout != rhel10cis_full_crypto_policy
  ansible.builtin.command: |
    update-crypto-policies --set "{{ rhel10cis_full_crypto_policy }}"
  changed_when: true
  notify:
    - Set reboot required
    - Restart sshd

- name: Reload firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded

- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: Restart postfix
  ansible.builtin.systemd:
    name: postfix
    state: restarted

- name: Reload dconf
  ansible.builtin.command: dconf update
  changed_when: true

- name: Grub2cfg
  ansible.builtin.command: "grub2-mkconfig -o /boot/grub2/grub.cfg"
  ignore_errors: true  # noqa ignore-errors
  changed_when: true
  notify: Set reboot required

- name: Restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted

- name: Restart journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted

- name: Systemd daemon reload
  ansible.builtin.systemd:
    daemon-reload: true

- name: Authselect update
  ansible.builtin.command: authselect apply-changes
  changed_when: true

## Auditd tasks note order for handlers to run

- name: Auditd rules reload
  when:
    - not system_is_container
    - not (discovered_auditd_immutable_check | bool) or
      "'No change' not in discovered_audit_rules_diff"
  ansible.builtin.command: augenrules --load
  changed_when: true
  listen: update auditd

- name: Audit immutable fact
  when:
    - discovered_audit_rules_updated.changed
    - auditd_immutable_check is defined
  ansible.builtin.debug:
    msg: "Reboot required for auditd to apply new rules as immutable set"
  notify: Set reboot required

- name: Stop auditd process
  when: not system_is_container
  ansible.builtin.command: systemctl kill auditd  # noqa command-instead-of-module
  changed_when: true
  listen: Restart auditd

- name: Start auditd process
  when: not system_is_container
  ansible.builtin.systemd_service:
    name: auditd
    state: started
  listen: Restart auditd

- name: Set reboot required
  ansible.builtin.set_fact:
    change_requires_reboot: true
