---
all:
  children:
    webservers:
      hosts:
        web-node-1:
          ansible_host: 192.168.122.10
        web-node-2:
          ansible_host: 192.168.122.11

    dbservers:
      hosts:
        db-node-1:
          ansible_host: 192.168.122.20
  vars:
    ansible_user: root
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
