#!/usr/bin/env bash
# one-time host prep. safe to re-run, every step is a no-op if already done.
set -euo pipefail

STATE_DIR=/var/lib/devops-pair-b
BUILD_KEY=~/.ssh/pairB_build

# shared state dir, not $HOME: jenkins runs as its own user and must see
# the same terraform state and golden image as your shell, otherwise the
# two disagree about who owns pool_b
if [ ! -d "$STATE_DIR" ]; then
  echo "creating $STATE_DIR (needs sudo, /var/lib is root-owned)"
  sudo mkdir -p "$STATE_DIR"/{images,tfstate/pair-b}
  sudo chown -R "$USER":"$USER" "$STATE_DIR"
else
  echo "$STATE_DIR already exists"
fi

# packer build key. cannot be generated by packer itself: http_content is
# evaluated in the source block, before the communicator exists, so
# build.SSHPublicKey is not available there
if [ ! -f "$BUILD_KEY" ]; then
  echo "generating $BUILD_KEY"
  ssh-keygen -t ed25519 -f "$BUILD_KEY" -N "" -q
else
  echo "$BUILD_KEY already exists"
fi

# the deploy key is NOT generated here, terraform creates it on apply

cat <<'EOF'

ready. next:
  cd packer    && packer init . && packer build .
  cd terraform && terraform init && terraform apply
EOF
