---
# TODO: Write your multi-play playbook here!
# Play 1: Target webservers and call the webserver role
# Play 2: Target dbservers and call the dbserver role

- name: Practice Playbook
  hosts: webservers
  become: false
  roles:
    - webserver
