---
- name: Configure Web Server Tier
  hosts: webservers
  become: false

  roles:
    - webserver

- name: Configure Database Server
  hosts: dbservers
  become: false

  vars_files:
    - group_vars/vault.yml
  roles:
    - dbserver
