---
# 1. Ensure Goss auditing runs after the script finishes
setup_audit: true
run_audit: true

# 2. Tell the CIS script to use journald for logging
rhel10cis_syslog: journald

# 3. Tell the CIS script to use a custom authselect profile
rhel10cis_authselect_custom_profile_name: custom_pair_b_profile

# 4. Fix NoneType bug in CIS script
rhel10cis_sshd_allowusers: ""

# 5. Only apply Level 1 Server rules (Task Requirement)
rhel10cis_level_2: false

# 6. Bypass GPG Key Check (ISO doesn't import GPG keys by default)
rhel10cis_rule_1_2_1_1: false

# 7. Force Ansible to download the JSON audit reports back to the Jenkins server!
fetch_audit_output: true
audit_output_destination: "./"
