---
- name: Display resolved dbserver variables
  ansible.builtin.debug:
    msg:
      - "Target Hostname: {{ inventory_hostname }}"
      - "Company Name: {{ company_name }}"
      - "MySQL Port {{ mysql_port }}"
      - "DB Name: {{ db_name }}"

- name: Demonstrate the decreyption vault variable
  ansible.builtin.debug:
    msg: "Decreted Secret: database password is {{vault_db_password}}"
