---
all:
  children:
    ingress:
      hosts:
        web-node-1:
          ansible_host: 192.168.122.48
    appservers:
      hosts:
        web-node-2:
          ansible_host: 192.168.122.205
    dbservers:
      hosts:
        db-node-1:
          ansible_host: 192.168.122.103
  vars:
    ansible_user: sysadmin
    ansible_ssh_private_key_file: /home/bunny/devops-pair-b/aeron-lab/terraform/.ssh/aeron_deploy
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
