---
- name: Hardening Pair B Nodes
  hosts: all
  become: true

  # PRECEDENCE LEVEL 2: Playbook VARs ovverides group_vars
  vars:
    # 1. Custom Login Banner (Task Tailoring Requirement)
    rhel10cis_warning_banner: "WARNING: Authorized Access Only - Pair B System"
    
    # 2. No account lockouts on failed password attempts (Task Tailoring Requirement)
    # We turn these rules OFF so the CIS script doesn't accidentally lock out
    # our root and user accounts, which would break our automated pipeline.
    # Note: These variable names are specific to RHEL10-CIS (Controls 5.3.2.1.1 to 5.3.2.1.3)
    # -------------------------------------------------------------------------
    # Pair B Constraint: No Account Lockouts Allowed
    # CIS 5.3.2.1 enforces the pam_faillock module (locking accounts after failed logins).
    # We MUST disable these because if an automated tool enters a wrong password,
    # the server will lock the account and permanently break our Jenkins pipeline!
    # -------------------------------------------------------------------------
    rhel10cis_rule_5_3_2_1_1: false # Disable 'deny' (number of failed attempts before lockout)
    rhel10cis_rule_5_3_2_1_2: false # Disable 'unlock_time' (how long the account stays locked)
    rhel10cis_rule_5_3_2_1_3: false # Disable 'fail_interval' (time window for failed attempts)

  # FORMAT DATA DISKS (Task Constraint)
  pre_tasks:
    - name: Format the first 2GB data disk (sda) to ext4
      community.general.filesystem:
        fstype: ext4
        dev: /dev/sda
    - name: Format the second 2GB data disk (sdb) to ext4
      community.general.filesystem:
        fstype: ext4
        dev: /dev/sdb

  # EXECUTE CIS HARDENING
  roles:
    - RHEL10-CIS
