---

- name: "6.2.3.1 | PATCH | Ensure rsyslog is installed"
  when:
    - rhel10cis_rule_6_2_3_1
    - rhel10cis_rsyslog_ansiblemanaged
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rsyslog
    - rule_6.2.3.1
    - NIST800-53R5_CM-6
  ansible.builtin.package:
    name: rsyslog
    state: present

- name: "6.2.3.2 | PATCH | Ensure rsyslog service is enabled and active"
  when:
    - rhel10cis_rule_6_2_3_2
    - rhel10cis_rsyslog_ansiblemanaged
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rsyslog
    - rule_6.2.3.2
    - NIST800-53R5_AU-2
    - NIST800-53R5_AU-3
    - NIST800-53R5_AU-12
  ansible.builtin.systemd:
    name: rsyslog
    enabled: true
    state: started

- name: "6.2.3.3 | PATCH | Ensure journald is configured to send logs to rsyslog"
  when:
    - rhel10cis_rule_6_2_3_3
    - rhel10cis_rsyslog_ansiblemanaged
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rule_6.2.3.3
    - NIST800-53R5_AC-3
    - NIST800-53R5_AU-2
    - NIST800-53R5_AU-4
    - NIST800-53R5_AU-12
    - NIST800-53R5_MP-2
  ansible.builtin.template:
    src: etc/systemd/journald.conf.d/forwardtosyslog.conf.j2
    dest: /etc/systemd/journald.conf.d/forwardtosyslog.conf
    owner: root
    group: root
    mode: 'u-x,g-wx,o-rwx'
  notify: Restart journald

- name: "6.2.3.4 | PATCH | Ensure rsyslog log file creation mode is configured"
  when:
    - rhel10cis_rule_6_2_3_4
    - rhel10cis_rsyslog_ansiblemanaged
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rsyslog
    - rule_6.2.3.4
    - NIST800-53R5_AC-3
    - NIST800-53R5_AC-6
    - NIST800-53R5_MP-2
  ansible.builtin.lineinfile:
    path: /etc/rsyslog.conf
    regexp: "^\\$FileCreateMode"
    line: "$FileCreateMode 0640"
  notify: Restart rsyslog

- name: "6.2.3.5 | PATCH | Ensure rsyslog logging is configured"
  when:
    - rhel10cis_rule_6_2_3_5
    - rhel10cis_rsyslog_ansiblemanaged
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rsyslog
    - rule_6.2.3.5
    - NIST800-53R5_AU-2
    - NIST800-53R5_AU-7
    - NIST800-53R5_AU-12
  block:
    - name: "6.2.3.5 | AUDIT | Ensure rsyslog logging is configured | rsyslog current config message out"
      ansible.builtin.shell: |
        set -o pipefail
        grep -Ev "^#|^$" /etc/rsyslog.conf
      args:
        executable: "{{ rhel10cis_shell_executable }}"
      changed_when: false
      failed_when: false
      check_mode: false
      register: discovered_configured_rsyslog

    - name: "6.2.3.5 | AUDIT | Ensure rsyslog logging is configured | rsyslog current config message out"
      ansible.builtin.debug:
        msg:
          - "These are the current logging configurations for rsyslog, please review:"
          - "{{ discovered_configured_rsyslog.stdout_lines }}"

    - name: "6.2.3.5 | PATCH | Ensure rsyslog logging is configured | mail.* log setting"
      ansible.builtin.blockinfile:
        path: /etc/rsyslog.conf
        marker: "# {mark} MAIL LOG SETTINGS - CIS benchmark - Ansible-lockdown"
        block: |
          # mail logging additions to meet CIS standards
          mail.*                                                  -/var/log/mail
          mail.info                                               -/var/log/mail.info
          mail.warning                                            -/var/log/mail.warning
          mail.err                                                /var/log/mail.err
        insertafter: "# Log all the mail messages in one place."
      notify: Restart rsyslog

    - name: "6.2.3.5 | PATCH | Ensure rsyslog logging is configured | news.crit log setting"
      ansible.builtin.blockinfile:
        path: /etc/rsyslog.conf
        state: present
        marker: "# {mark} NEWS LOG SETTINGS - CIS benchmark - Ansible-lockdown"
        block: |
          # news logging additions to meet CIS standards
          news.crit                                               -/var/log/news/news.crit
          news.notice                                             -/var/log/news/news.crit
        insertafter: "# Save news errors of level crit and higher in a special file."
      notify: Restart rsyslog

    - name: "6.2.3.5 | PATCH | Ensure rsyslog logging is configured | Misc. log setting"
      ansible.builtin.blockinfile:
        path: /etc/rsyslog.conf
        state: present
        marker: "# {mark} MISC. LOG SETTINGS - CIS benchmark - Ansible-lockdown"
        block: |
          # misc. logging additions to meet CIS standards
          *.=warning;*.=err                                        -/var/log/warn
          *.crit                                                   /var/log/warn
          *.*;news.none                                            /var/log/messages
        insertbefore: '# ### sample forwarding rule ###'
      notify: Restart rsyslog

    - name: "6.2.3.5 | PATCH | Ensure rsyslog logging is configured | Local log settings"
      ansible.builtin.blockinfile:
        path: /etc/rsyslog.conf
        state: present
        marker: "#{mark} LOCAL LOG SETTINGS - CIS benchmark - Ansible-lockdown"
        block: |
          # local log settings to meet CIS standards
          local0,local1.*                                          -/var/log/localmessages
          local2,local3.*                                          -/var/log/localmessages
          local4,local5.*                                          -/var/log/localmessages
          local6,local7.*                                          -/var/log/localmessages
          *.emerg                                                    :omusrmsg:*
        insertafter: "#### RULES ####"
      notify: Restart rsyslog

    - name: "6.2.3.5 | PATCH | Ensure rsyslog logging is configured | Auth Settings"
      ansible.builtin.blockinfile:
        path: /etc/rsyslog.conf
        state: present
        marker: "#{mark} Auth SETTINGS - CIS benchmark - Ansible-lockdown"
        block: |
          # Private settings to meet CIS standards
          auth,authpriv.*                                           /var/log/secure
        insertafter: "#### RULES ####"
      notify: Restart rsyslog

    - name: "6.2.3.5 | PATCH | Ensure rsyslog logging is configured | Cron Settings"
      ansible.builtin.blockinfile:
        path: /etc/rsyslog.conf
        state: present
        marker: "#{mark} Cron SETTINGS - CIS benchmark - Ansible-lockdown"
        block: |
          # Cron settings to meet CIS standards
          cron.*                                                   /var/log/cron
        insertafter: "#### RULES ####"
      notify: Restart rsyslog

- name: "6.2.3.6 | PATCH | Ensure rsyslog is configured to send logs to a remote log host"
  when:
    - rhel10cis_rule_6_2_3_6
    - rhel10cis_remote_log_server
    - rhel10cis_rsyslog_ansiblemanaged
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rsyslog
    - rule_6.2.3.6
    - NIST800-53R5_AU-6
  ansible.builtin.blockinfile:
    path: /etc/rsyslog.conf
    state: present
    block: |
      # target can be IP or FQDN
      *.* action(type="omfwd" target="{{ rhel10cis_remote_log_host }}" port="{{ rhel10cis_remote_log_port }}" protocol="{{ rhel10cis_remote_log_protocol }}" action.resumeRetryCount="{{ rhel10cis_remote_log_retrycount }}" queue.type="LinkedList" queue.size="{{ rhel10cis_remote_log_queuesize }}")
    insertafter: EOF
  failed_when:
    - discovered_rsyslog_remote_host is failed
    - discovered_rsyslog_remote_host.rc != 257
  register: discovered_rsyslog_remote_host
  notify: Restart rsyslog

- name: "6.2.3.7 | PATCH | Ensure rsyslog is not configured to receive logs from a remote client"
  when:
    - rhel10cis_rule_6_2_3_7
    - rhel10cis_rsyslog_ansiblemanaged
    - not rhel10cis_system_is_log_server
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rsyslog
    - rule_6.2.3.7
    - NIST800-53R5_AU-2
    - NIST800-53R5_AU-7
    - NIST800-53R5_AU-12
    - NIST800-53R5_CM-6
  ansible.builtin.replace:
    path: /etc/rsyslog.conf
    regexp: "{{ item }}"
    replace: "#\\1"
  loop:
    - "^(\\$ModLoad imtcp)"
    - "^(\\$InputTCPServerRun)"
    - '^(module\(load="imtcp"\))'
    - '^(input\(type="imtcp")'
  notify: Restart rsyslog

- name: "6.2.3.8 | PATCH | Ensure rsyslog logrotate is configured"
  when:
    - rhel10cis_rule_6_2_3_8
    - rhel10cis_rsyslog_ansiblemanaged
  tags:
    - level1-server
    - level1-workstation
    - manual
    - patch
    - logrotate
    - rule_6.2.3.8
    - NIST800-53R5_AU-8
  block:
    - name: "6.2.3.8 | PATCH | Ensure rsyslog logrotate is configured | installed"
      ansible.builtin.package:
        name: logrotate
        state: present

    - name: "6.2.3.8 | PATCH | Ensure rsyslog logrotate is configured | scheduled"
      ansible.builtin.systemd:
        name: logrotate.timer
        state: started
        enabled: true

    - name: "6.2.3.8 | PATCH | Ensure rsyslog logrotate is configured | set rsyslog conf"
      ansible.builtin.template:
        src: etc/logrotate.d/rsyslog_log.j2
        dest: /etc/logrotate.d/rsyslog_log.conf
        owner: root
        group: root
        mode: 'u-x,g-wx,o-rwx'
